### ISSUE TITLE
spatial regression?

### ISSUE THREAD

**Issue by weikang9009** [sjsrey/pysalworkshop#4]
Do we want to add spatial regression? It is listed in the [NARSC program](http://www.narsc.org/newsite/wp-content/uploads/2019/06/pysal.pdf)

**Comment by sjsrey** [comment]
I think we can leave it out and send a new outline on wednesday. Unless you want to add materials?

**Comment by weikang9009** [comment]
I do not think we will have time to cover that - the current content already has many amazing additions (contextily, shapely, visualization, etc)
